export { default as Hero } from './hero/Hero';
export { default as Navbar } from './navbar/Navbar'
export { default as About } from './about/About';
export { default as Support } from './support/Support';
export { default as Footer } from './footer/Footer';
export { default as Cve } from './cve/Cve';
export { default as Ecotech } from './ecotech/Ecotech';
export { default as Contact } from './contact/Contact';
export { default as Faq } from './faq/Faq';
export { default as Events } from './events/Events';
